export const MESSAGE_TYPE = Object.freeze({
  API_TOKEN_STATUS_UPDATE: 1,
  CURRENT_ENTRY_UPDATE: 2,
  DELETE_CURRENT_ENTRY: 3,
  RESUME_LAST_ENTRY: 4,
  STOP_CURRENT_ENTRY: 5,
  ENTRIES_LOG_UPDATE: 6,
});
