name: Style guide check
on:
  push:
    branches:
      - ci

jobs:
  run:
    name: Launch eslint with google stryle guide
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint
