name: Collect code coverage
on:
  push:
    branches:
      - master
      - feature/**

jobs:
  run:
    name: Run tests and collect results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TOKEN }}
        with:
          coverageCommand: yarn test:unit --maxWorkers=4 --collectCoverage
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          fail_ci_if_error: true
