name: Collect code coverage
on:
  push:
    branches:
      - ci

jobs:
  run:
    name: Run tests and collect results
    runs-on: ubuntu-latest
    env:
      VUE_APP_CAPTCHA_SECRET: ${{ secrets.VUE_APP_CAPTCHA_SECRET }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Install Dependencies
        run: yarn install

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run tests with collect coverage
        run: yarn test:unit --maxWorkers=4 --collectCoverage

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          fail_ci_if_error: true
